from collections import deque

grid =[]
with open("input.txt") as f : 
    grid = [list(line.strip()) for line in f.readlines()]

def in_bounds(point,grid) : 
    return point[0] >= 0 and point[1] >= 0 and point[0] < len(grid) and point[1] <len(grid[0])

def add(first,second): 
    return (first[0]+second[0],first[1]+second[1])

to_be_explored = set( (x,y) for x in range(len(grid)) for y in range(len(grid[0])))
shifts = [(-1,0),(1,0),(0,1),(0,-1)]

def find_components(grid) :
    components = {}
    explored = set()
    #For each point that already hasn't been found in a cluster
    while to_be_explored:
        point = to_be_explored.pop()
        # Initialize (if the type is new, we initialize it)
        plant_type = grid[point[0]][point[1]]
        if plant_type not in components : 
            components[plant_type] = []
        # Initialize queue
        queue = deque()
        queue.append(point)
        component = [point]
        while queue : 
            current = queue.pop()
            for shift in shifts :
                next = add(current,shift)
                # If next is in bounds, has the same plant type and is not explored 
                if in_bounds(next,grid) and grid[next[0]][next[1]] == plant_type and next in to_be_explored:
                        to_be_explored.remove(next)
                        component.append(next)
                        queue.append(next)
        components[plant_type].append(component)

    return components

def l1_distance(first, second) : 
    return abs(first[0]-second[0])+abs(first[1]-second[1])

# Computes the number of connected components of the
# graph generated by the edge set describing the outgoing edges
def find_number_of_sides(perimiter) : 
    edge_set = {}
    #Generate edge set
    for first_edge in perimiter : 
        if first_edge not in edge_set : 
            edge_set[first_edge] = []
        for second_edge in perimiter:
            first_dist = l1_distance(first_edge[0],second_edge[0])
            second_dist = l1_distance(first_edge[1],second_edge[1])
            if first_dist == 1 and second_dist == 1 : 
                edge_set[first_edge].append(second_edge)
    # Do a BFS once again to find all connected components
    unexplored_edges = perimiter.copy()
    number_of_sides = 0
    while unexplored_edges : 
        edge = unexplored_edges.pop()
        queue = deque()
        queue.append(edge)
        while queue : 
            current = queue.pop()
            neighbors = edge_set[current] 
            for neighbor in neighbors : 
                if neighbor in unexplored_edges : 
                    unexplored_edges.remove(neighbor)
                    queue.append(neighbor)
        number_of_sides +=1
    return number_of_sides


def find_permiter(component, grid) : 
    perimiter = set()
    point = component[0]
    type = grid[point[0]][point[1]]
    for point in component : 
        for shift in shifts : 
            possible_neighbor = add(point,shift)
            if (in_bounds(possible_neighbor,grid) and grid[possible_neighbor[0]][possible_neighbor[1]] != type) or not in_bounds(possible_neighbor,grid) : 
                edge = (point,possible_neighbor)
                perimiter.add(edge)
    return  perimiter

      

components = find_components(grid)


prize = 0
reduced = 0
for key in components : 
    type_components = components[key]
    for component in type_components : 
        perimiter = find_permiter(component,grid)
        prize+=len(perimiter)*len(component)
        reduced += find_number_of_sides(perimiter)*len(component)
print("Part 1", prize)
print("Part 2", reduced)
